push dockerfile changes

diff --git a/test-pp-op/dockerfile/Dockerfile.op-program b/test-pp-op/dockerfile/Dockerfile.op-program
--- a/test-pp-op/dockerfile/Dockerfile.op-program
+++ b/test-pp-op/dockerfile/Dockerfile.op-program
@@ -1,13 +1,20 @@
 FROM op-stack:v1.13.4 AS geth-builder
 
+RUN apt-get update && apt-get install -y --no-install-recommends git
+
 WORKDIR /app/op-geth
 # Must build op-stack with migrate feature (in specific branch)
+RUN git stash
 RUN git checkout feat/cliff/migrate-test
 RUN git pull origin feat/cliff/migrate-test
 RUN go build -ldflags '-extldflags "-static"' -o build/bin/geth ./cmd/geth
 
 # 2nd stage
 FROM op-stack:v1.13.4 AS builder
+
+ARG CHAIN_ID
+RUN test -n "${CHAIN_ID}" || (echo "ERROR: CHAIN_ID is not set" && exit 1)
+RUN echo "CHAIN_ID: ${CHAIN_ID}"
 
 # Install dependencies (docker CLI, make, etc.)
 RUN apt-get update && \
@@ -19,8 +26,8 @@ RUN apt-get update && \
 
 WORKDIR /app
 COPY .env .
-COPY config-op/rollup.json /app/op-program/chainconfig/configs/196-rollup.json
-COPY config-op/genesis.gz.json /app/op-program/chainconfig/configs/196-genesis-l2.json
+COPY config-op/rollup.json /app/op-program/chainconfig/configs/${CHAIN_ID}-rollup.json
+COPY config-op/genesis.gz.json /app/op-program/chainconfig/configs/${CHAIN_ID}-genesis-l2.json
 # Download deps for building this binary. We will cache this inside image.
 RUN echo '🚀 Building reproducible-prestate...' && \
     make reproducible-prestate || echo "⚠️ Make failed during build, check setup"
